FROM node:18-alpine

WORKDIR /app

# Install dependencies (using ci for deterministic builds)
COPY package*.json ./
RUN npm ci --silent

# Copy source code
COPY . .

# React default port
EXPOSE 3000

CMD ["npm", "start"]
