/**
 * Bit-match the C++ HashEmbedder port against orchestration/rag/embed.py.
 *
 * The fixture file `rag_embed_fixtures.txt` is generated by the companion
 * Python helper tests/rag/gen_embed_fixtures.py and committed alongside this
 * test. Format: one fixture per record, separated by "\n---\n":
 *
 *     <text line(s)>
 *     ===VEC===
 *     v0,v1,...,v767     (6-decimal floats, comma-separated)
 *
 * Bit-match means: the C++ rag::vec_literal(hash_embed(text)) must equal
 * "[v0,v1,...,v767]" byte-for-byte — that is exactly what is sent to
 * pgvector by both runtimes.
 */
#include "rag_client.h"
#include "rag_embed.h"

#include <cassert>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct Fixture { std::string text; std::string expected_literal; };

std::vector<Fixture> load(const std::string& path) {
    std::ifstream in(path);
    if (!in) {
        std::cerr << "could not open fixtures: " << path << std::endl;
        std::exit(2);
    }
    std::vector<Fixture> out;
    std::string line;
    Fixture cur;
    bool in_vec = false;
    std::ostringstream txt, vec;
    auto flush = [&]() {
        if (txt.tellp() == std::streampos(0) && vec.tellp() == std::streampos(0)) return;
        cur.text = txt.str();
        if (!cur.text.empty() && cur.text.back() == '\n') cur.text.pop_back();
        cur.expected_literal = "[" + vec.str() + "]";
        out.push_back(cur);
        cur = {}; txt.str(""); txt.clear(); vec.str(""); vec.clear();
        in_vec = false;
    };
    while (std::getline(in, line)) {
        if (line == "---") { flush(); continue; }
        if (line == "===VEC===") { in_vec = true; continue; }
        if (in_vec) vec << line; else txt << line << '\n';
    }
    flush();
    return out;
}

} // namespace

int main(int argc, char** argv) {
    std::string path = (argc >= 2)
        ? argv[1]
        : std::string("tests/cpp/rag_embed_fixtures.txt");
    auto fixtures = load(path);
    if (fixtures.empty()) {
        std::cerr << "no fixtures loaded from " << path << std::endl;
        return 2;
    }
    int failures = 0;
    for (const auto& f : fixtures) {
        auto vec = rag::hash_embed(f.text);
        std::string got = rag::vec_literal(vec);
        if (got != f.expected_literal) {
            ++failures;
            std::cerr << "MISMATCH for text=" << f.text.substr(0, 40) << "...\n";
            // Show the first differing offset for quick diagnosis.
            size_t i = 0;
            while (i < got.size() && i < f.expected_literal.size() &&
                   got[i] == f.expected_literal[i]) ++i;
            std::cerr << "  first diff at offset " << i << ": cpp='"
                      << got.substr(i, 24) << "' py='"
                      << f.expected_literal.substr(i, 24) << "'\n";
        }
    }
    std::cout << "rag_embed_test: " << fixtures.size() - failures
              << "/" << fixtures.size() << " fixtures matched" << std::endl;
    return failures == 0 ? 0 : 1;
}
