import { useMemo } from 'react';

/** Builds the prop bag passed to the active layout shell (Brewlate / Classic). */
export function useAppLayoutProps(props) {
  const {
    online, activeAgents, modes, activeMode, kvReadings, kvFetchFailed, hostMemory,
    responses, agentErrors, finalAnswer, loading, error, history, lastMeta,
    currentSession, backend, switchBackend,
    showConfig, showHistory, showConfigPanel, deployPending,
    showHelp, showConverter, showRagAdmin, showCachePanel, cacheStatus, useRag,
    flatPickAgent, excludedBreaker, stageOutputs,
    warningsByModeWithMemory, memoryPressure, theme, layout,
    pendingPrompt, selectedPrompt, selectedTemperature,
    handleModeChange, handleClearCache,
    handleToggleConfig, handleToggleHistory, handleOpenConverter,
    handleOpenRagAdmin, handleOpenCachePanel, handleOpenHelp,
    setTheme, setLayout, handleDeployed,
    handleHistorySelect, handleSubmit, handleQualityPass,
    setSelectedPrompt, handleFollowUp, handleClearSession, handleSwitchSession,
    handleSaveCode, setFlatPickAgent, handleSendBestContinue, setUseRag,
    handleExpandProgrammer,
    setShowHelp, setShowRagAdmin, setShowCachePanel,
    budgetExhausted,
  } = props;

  return useMemo(() => ({
    online,
    activeAgents,
    modes,
    activeMode,
    kvReadings,
    kvFetchFailed,
    hostMemory,
    responses,
    agentErrors,
    finalAnswer,
    loading,
    error,
    history,
    lastMeta,
    currentSession,
    backend,
    switchBackend,
    showConfig,
    showHistory,
    showConfigPanel,
    deployPending,
    showHelp,
    showConverter,
    showRagAdmin,
    showCachePanel,
    cacheStatus,
    useRag,
    flatPickAgent,
    excludedBreaker,
    stageOutputs,
    warningsByMode: warningsByModeWithMemory,
    memoryPressure,
    theme,
    layout,
    pendingPrompt,
    selectedPrompt,
    selectedTemperature,
    onModeChange: handleModeChange,
    onClearCache: handleClearCache,
    onToggleConfig: handleToggleConfig,
    onToggleHistory: handleToggleHistory,
    onOpenConverter: handleOpenConverter,
    onOpenRagAdmin: handleOpenRagAdmin,
    onOpenCachePanel: handleOpenCachePanel,
    onOpenHelp: handleOpenHelp,
    onCloseHelp: () => setShowHelp(false),
    onCloseRagAdmin: () => setShowRagAdmin(false),
    onCloseCachePanel: () => setShowCachePanel(false),
    onSetTheme: setTheme,
    onSetLayout: setLayout,
    onDeployed: handleDeployed,
    onHistorySelect: handleHistorySelect,
    onSubmit: handleSubmit,
    onQualityPass: handleQualityPass,
    onPromptConsumed: () => setSelectedPrompt(null),
    onFollowUp: handleFollowUp,
    onClearSession: handleClearSession,
    onSwitchSession: handleSwitchSession,
    onSaveCode: handleSaveCode,
    onPickFlatAgent: setFlatPickAgent,
    onSendBestContinue: handleSendBestContinue,
    onUseRagChange: setUseRag,
    onExpandProgrammer: handleExpandProgrammer,
    budgetExhausted,
  }), [
    online, activeAgents, modes, activeMode, kvReadings, kvFetchFailed, hostMemory,
    responses, agentErrors, finalAnswer, loading, error, history, lastMeta,
    currentSession, backend, switchBackend, showConfig, showHistory, showConfigPanel,
    deployPending, showHelp, showConverter, showRagAdmin, showCachePanel, cacheStatus,
    useRag, flatPickAgent, excludedBreaker, stageOutputs, warningsByModeWithMemory, memoryPressure, theme, layout,
    pendingPrompt, selectedPrompt, selectedTemperature, handleModeChange, handleClearCache,
    handleToggleConfig, handleToggleHistory, handleOpenConverter, handleOpenRagAdmin,
    handleOpenCachePanel, handleOpenHelp, setTheme, setLayout, handleDeployed,
    handleHistorySelect, handleSubmit, handleQualityPass, setSelectedPrompt, handleFollowUp, handleClearSession,
    handleSwitchSession, handleSaveCode, setFlatPickAgent, handleSendBestContinue, handleExpandProgrammer,
    setShowHelp, setShowRagAdmin, setShowCachePanel, setUseRag, budgetExhausted,
  ]);
}
